# Site settings
title: Geir og Marita
description: > # this means to ignore newlines until "baseurl:"
  Business cards for Geir Tønnessen and Marita Nodland.
  Use the links to our blogs, project pages and social media presences
  if you want to contact us.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.GeirOgMarita.net" # the base hostname & protocol for your site
twitter_username: geirbert
github_username:  GeirT

# Build settings
exclude: [Gemfile, Gemfile.lock, about.md, README.md]
markdown: kramdown
